Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,16 +1,17 @@
+                                                                
 #!/bin/bash
 
 rm ~/x
-echo "                                                                     ";
-echo "                                                                   / ";
-echo "                                                                 /  ";
-echo "       .    ,                        ,/    ";
-echo "   /'    )  \  /   /'    )--/'    )--/'    )--)'    )--/'    /      ";
-echo " /(,/'    '   '---,   /'       /'    /' /'       /'    /        ";
-echo "(/' _(,/   (,/   (,/' /'        (,/(        ";
-echo "                                                                     ";
-echo " by ShephardOS  // BoxWine made by: ShephardOS          ";
-echo "                                                                     ";
+echo "                                                                     ";
+echo "                                                                   / ";
+echo "                                                                 /  ";
+echo "       .    ,                        _,/    ";
+echo "   /'    )  \  /   /'    )--/'    )--/'    )--)'    )--/'    /      ";
+echo " /(___,/'    \'   '---,   /'       /'    /' /'       /'    /        ";
+echo "(/' \_(_,/   (_,/   (_,/' /'        (_,/(        ";
+echo "                                                                     ";
+echo " by ShephardOS             ";
+echo "                                                                     ";
 
 echo "Installing termux-am"
 pkg install termux-am -y &>/dev/null
@@ -18,12 +19,12 @@ yes | pkg install wget; clear
 termux-setup-storage & sleep 4 &>/dev/null
 
 while true; do
-    if [ -d ~/storage/shared ]; then
-        break
-    else
-        echo "Storage permission denied"
-    fi
-    sleep 3
+    if [ -d ~/storage/shared ]; then
+        break
+    else
+        echo "Storage permission denied"
+    fi
+    sleep 3
 done
 
 echo "Installing termux packages"
@@ -44,37 +45,37 @@ pkg install hashdeep -y &>/dev/null
 pkg install termux-x11-nightly -y &>/dev/null
 
 if [ -e $PREFIX/glibc ]; then
-    echo -n "Removing previous glibc. Continue? (Y/n) "
-    read i
-    if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
-        rm -rf $PREFIX/glibc
-    else
-        return 1
-    fi
+    echo -n "Removing previous glibc. Continue? (Y/n) "
+    read i
+    if [ "$i" = "Y" ] || [ "$i" = "y" ]; then
+        rm -rf $PREFIX/glibc
+    else
+        return 1
+    fi
 fi
 
-echo "Installing boxwine"
+echo "Installing BoxWine"
 
 function wget-git-q {
-    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
-    return $?
+    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: glpat-kj--11qKof3MZXBayzRV" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O $2
+    return $?
 }
 
 echo "Updating package manager"
 mkdir -p $PREFIX/glibc/opt/package-manager/installed
 
-echo "PRIVATE_TOKEN=glpat-6LE7R9PQ7zb6zsx4x3be PROJECT_ID=64704412">$PREFIX/glibc/opt/package-manager/token
+echo "PRIVATE-TOKEN=glpat-kj--11qKof3MZXBayzRV
+PROJECT_ID=64704412">$PREFIX/glibc/opt/package-manager/token
 
 . $PREFIX/glibc/opt/package-manager/token
 if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
-    echo "Download failed"
-    return 1
+    echo "Download failed"
+    return 1
 fi
 . $PREFIX/glibc/opt/package-manager/package-manager
 sync-all
 
 sync-package wine-9.3-vanilla-wow64
 
-ln -sf $PREFIX/glibc/opt/scripts/exscord $PREFIX/bin/exscord
-echo "To start - type "exscord""
-
+ln -sf $PREFIX/glibc/opt/scripts/boxwine $PREFIX/bin/boxwine
+echo "To start - type \"boxwine\""
